### ISSUE TITLE
Near-term to-do list

### ISSUE THREAD

**Issue by KarstModel** [KarstModel/scallop-abrasion#9]
Inspired by Fornari, Walter, Francesco Picano, and Luca Brandt. “Sedimentation of Finite-Size Spheres in Quiescent and Turbulent Environments.” ArXiv Preprint ArXiv:1503.06148, 2015.

- [ ] review Kolmogorov scale, and how it may affect our treatment of particle sizes with respect to fluid characteristics.

- [x] for entire set of impact velocities, plot all velocities in histogram. 
>>>>>should be Gaussian
>>>>>mean should be less than Stokes settling velocity

- [ ] revise particle Reynold's number calculation to invoke Archimedes number?
![image](https://user-images.githubusercontent.com/17818298/101801304-27ce9c00-3adc-11eb-9f73-f107321e440e.png)

- [x] extract and plot each particle's velocities as function of time
